# Generated by Django 2.0.5 on 2018-05-10 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summoner',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('profileIconId', models.IntegerField()),
                ('name', models.CharField(max_length=25)),
                ('summonerLevel', models.BigIntegerField()),
                ('revisionDate', models.BigIntegerField()),
                ('accountId', models.BigIntegerField()),
                ('lastUpdate', models.BigIntegerField()),
                ('favChamp', models.IntegerField()),
            ],
        ),
    ]
