# Generated by Django 2.0.5 on 2018-05-10 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summoner',
            name='id',
        ),
        migrations.AlterField(
            model_name='summoner',
            name='accountId',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
