# Generated by Django 2.0.5 on 2018-05-13 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0002_auto_20180510_0430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summoner',
            old_name='accountId',
            new_name='id',
        ),
    ]
