# Generated by Django 2.0.5 on 2018-05-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0003_auto_20180513_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summoner',
            name='favChamp',
            field=models.IntegerField(null=True),
        ),
    ]
