# Generated by Django 2.0.5 on 2018-05-17 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0005_gamemode_map_summonerspell'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summonerspell',
            old_name='key',
            new_name='id',
        ),
    ]
