# Generated by Django 2.0.5 on 2018-05-17 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0006_auto_20180517_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summonerspell',
            old_name='id',
            new_name='key',
        ),
    ]
