# Generated by Django 2.0.5 on 2018-05-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0007_auto_20180517_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='summonerspell',
            name='id',
            field=models.CharField(default='UNKNOWN', max_length=20),
        ),
    ]
