# Generated by Django 2.0.5 on 2018-05-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0008_summonerspell_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('map', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
    ]
